# Generated by Django 5.1.6 on 2025-03-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can View'), ('can_create', 'Can Create'), ('can_edit', 'Can Edit'), ('can_delete', 'Can Delete')]},
        ),
    ]
